version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: kenan123
    volumes:
      - ./../postgres_volumes:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py test Askmedical"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


