# Generated by Django 3.2.3 on 2021-06-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Askmedical', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
