# Generated by Django 3.2.3 on 2021-06-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Askmedical', '0003_auto_20210609_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
