# Generated by Django 3.2.3 on 2021-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Askmedical', '0004_article_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('taglink', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='Askmedical.Tag'),
        ),
    ]
